use_frameworks!

platform :ios, '10.0'

target 'SupportSystem_Example' do
  pod 'SSZipArchive', '~> 2.4.2'
  pod 'SupportSystem', :path => '../'

  target 'SupportSystem_Tests' do
    inherit! :search_paths

    
  end
end
 
